## 3-Input Gates

In [1]:
import numpy as np

In [2]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

def feed_forward(X,W_L1,W_L2):
    
    O_L1 = sigmoid(np.matmul(X,W_L1))
    O_L2 = sigmoid(np.matmul(O_L1,W_L2))
    
    return O_L1,O_L2

def back_propagation(X,alpha,W_L1,W_L2,O_L1,O_L2,expected):
    E_o = O_L2*(1-O_L2)*(expected-O_L2);
    
    E_h = E_o * (O_L1*(1-O_L1)*W_L2.reshape(1,4))
    
    W_L2 = W_L2 + (alpha * E_o * O_L1).reshape(4,1)
    
    X=X.reshape(6,1)

    mask = np.array([[1,1,1,0],[1,1,1,0],[1,1,1,0],[1,0,0,0],[0,1,0,0],[0,0,1,1]])
    W_L1 = ( W_L1 + (alpha * np.matmul(X,E_h)) ) * mask
    
    return W_L1,W_L2
    
def Learn(table,itr,alpha):
    X = table[:,0:3]
    expected = table[:,-1]
    ones = np.ones(24).reshape(8,3)
    X = np.hstack((X,ones))

    mask = np.array([[1,1,1,0],[1,1,1,0],[1,1,1,0],[1,0,0,0],[0,1,0,0],[0,0,1,1]])
    W_L1 = np.random.randn(24).reshape(6,4) * mask
    W_L1[5][3]=np.inf
    W_L2 = np.random.randn(4).reshape(4,1)
    
    for _ in range(itr):
        
        for i in range(8):
            print("Sample(",i,")")
            print(X[i],expected[i])
            O_L1,O_L2 = feed_forward(X[i],W_L1,W_L2)
            print("O_L1=",O_L1,"\nO_L2=",O_L2)
            W_L1,W_L2 = back_propagation(X[i],alpha,W_L1,W_L2,O_L1,O_L2,expected[i])
        
        print("")
    return W_L1,W_L2




In [3]:
table = np.array([
    [0,0,0,0],
    [0,0,1,1],
    [0,1,0,1],
    [0,1,1,1],
    [1,0,0,1],
    [1,0,1,1],
    [1,1,0,1],
    [1,1,1,0]
])
Learn(table,1000,0.7)

Sample( 0 )
[0. 0. 0. 1. 1. 1.] 0
O_L1= [0.76145496 0.66057132 0.54697157 1.        ] 
O_L2= [0.90684958]
Sample( 1 )
[0. 0. 1. 1. 1. 1.] 1
O_L1= [0.5151194  0.87308206 0.13386332 1.        ] 
O_L2= [0.76145869]
Sample( 2 )
[0. 1. 0. 1. 1. 1.] 1
O_L1= [0.94292208 0.35025231 0.41817767 1.        ] 
O_L2= [0.93098519]
Sample( 3 )
[0. 1. 1. 1. 1. 1.] 1
O_L1= [0.85054249 0.6538602  0.08566134 1.        ] 
O_L2= [0.87526736]
Sample( 4 )
[1. 0. 0. 1. 1. 1.] 1
O_L1= [0.80299643 0.47982995 0.49112849 1.        ] 
O_L2= [0.91369416]
Sample( 5 )
[1. 0. 1. 1. 1. 1.] 1
O_L1= [0.58518258 0.76344534 0.11190264 1.        ] 
O_L2= [0.80664291]
Sample( 6 )
[1. 1. 0. 1. 1. 1.] 1
O_L1= [0.95603205 0.20175879 0.36901053 1.        ] 
O_L2= [0.93869629]
Sample( 7 )
[1. 1. 1. 1. 1. 1.] 0
O_L1= [0.88350001 0.46897482 0.07102771 1.        ] 
O_L2= [0.89728368]

Sample( 0 )
[0. 0. 0. 1. 1. 1.] 0
O_L1= [0.76110372 0.66217128 0.54489962 1.        ] 
O_L2= [0.89826094]
Sample( 1 )
[0. 0. 1. 1. 1. 1.] 1
O_L1= [0.51

(array([[ 3.81456412,  1.5058823 , -3.59221437,  0.        ],
        [ 3.63942667,  1.13746533, -3.35213625,  0.        ],
        [ 4.87939105,  1.79487297, -4.80920332,  0.        ],
        [-0.64715941,  0.        ,  0.        ,  0.        ],
        [-0.        , -2.77913174,  0.        ,  0.        ],
        [-0.        ,  0.        ,  0.53475896,         inf]]),
 array([[ 4.58032972],
        [-4.60394393],
        [-4.60132061],
        [-0.94040896]]))