## 3-Input Gates

In [7]:
import numpy as np

In [8]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

def feed_forward(X,W_L1,W_L2):
    
    O_L1 = sigmoid(np.matmul(X,W_L1))
    O_L2 = sigmoid(np.matmul(O_L1,W_L2))
    
    return O_L1,O_L2

def back_propagation(X,alpha,W_L1,W_L2,O_L1,O_L2,expected):
    E_o = O_L2*(1-O_L2)*(expected-O_L2);
    
    E_h = E_o * (O_L1*(1-O_L1)*W_L2.reshape(1,4))
    
    W_L2 = W_L2 + (alpha * E_o * O_L1).reshape(4,1)
    
    X=X.reshape(6,1)

    mask = np.array([[1,1,1,0],[1,1,1,0],[1,1,1,0],[1,0,0,0],[0,1,0,0],[0,0,1,1]])
    W_L1 = ( W_L1 + (alpha * np.matmul(X,E_h)) ) * mask
    
    return W_L1,W_L2
    
def Learn(table,itr,alpha):
    X = table[:,0:3]
    expected = table[:,-1]
    ones = np.ones(24).reshape(8,3)
    X = np.hstack((X,ones))

    mask = np.array([[1,1,1,0],[1,1,1,0],[1,1,1,0],[1,0,0,0],[0,1,0,0],[0,0,1,1]])
    W_L1 = np.random.randn(24).reshape(6,4) * mask
    W_L1[5][3]=np.inf
    W_L2 = np.random.randn(4).reshape(4,1)
    
    for _ in range(itr):
        
        for i in range(8):
            print("Sample(",i,")")
            print(X[i],expected[i])
            O_L1,O_L2 = feed_forward(X[i],W_L1,W_L2)
            print("O_L2=",O_L2)
            W_L1,W_L2 = back_propagation(X[i],alpha,W_L1,W_L2,O_L1,O_L2,expected[i])
        
        print("")
    return W_L1,W_L2




In [9]:
table = np.array([
    [0,0,0,0],
    [0,0,1,1],
    [0,1,0,1],
    [0,1,1,1],
    [1,0,0,1],
    [1,0,1,1],
    [1,1,0,1],
    [1,1,1,0]
])
Learn(table,1000,1)

Sample( 0 )
[0. 0. 0. 1. 1. 1.] 0
O_L2= [0.44202168]
Sample( 1 )
[0. 0. 1. 1. 1. 1.] 1
O_L2= [0.24308073]
Sample( 2 )
[0. 1. 0. 1. 1. 1.] 1
O_L2= [0.3988438]
Sample( 3 )
[0. 1. 1. 1. 1. 1.] 1
O_L2= [0.35471939]
Sample( 4 )
[1. 0. 0. 1. 1. 1.] 1
O_L2= [0.57465583]
Sample( 5 )
[1. 0. 1. 1. 1. 1.] 1
O_L2= [0.56709449]
Sample( 6 )
[1. 1. 0. 1. 1. 1.] 1
O_L2= [0.6378594]
Sample( 7 )
[1. 1. 1. 1. 1. 1.] 0
O_L2= [0.62813113]

Sample( 0 )
[0. 0. 0. 1. 1. 1.] 0
O_L2= [0.70986434]
Sample( 1 )
[0. 0. 1. 1. 1. 1.] 1
O_L2= [0.54117058]
Sample( 2 )
[0. 1. 0. 1. 1. 1.] 1
O_L2= [0.65057244]
Sample( 3 )
[0. 1. 1. 1. 1. 1.] 1
O_L2= [0.61072554]
Sample( 4 )
[1. 0. 0. 1. 1. 1.] 1
O_L2= [0.72921883]
Sample( 5 )
[1. 0. 1. 1. 1. 1.] 1
O_L2= [0.72117208]
Sample( 6 )
[1. 1. 0. 1. 1. 1.] 1
O_L2= [0.73600662]
Sample( 7 )
[1. 1. 1. 1. 1. 1.] 0
O_L2= [0.72539532]

Sample( 0 )
[0. 0. 0. 1. 1. 1.] 0
O_L2= [0.7822953]
Sample( 1 )
[0. 0. 1. 1. 1. 1.] 1
O_L2= [0.66292544]
Sample( 2 )
[0. 1. 0. 1. 1. 1.] 1
O_L2= [0.7206

(array([[-2.4992418 ,  4.14892811,  3.68946533,  0.        ],
        [-1.3799916 ,  4.3368129 ,  3.47708856,  0.        ],
        [-0.23015305,  4.51725433,  3.33655048,  0.        ],
        [ 1.82168447, -0.        ,  0.        ,  0.        ],
        [ 0.        , -2.30578804,  0.        ,  0.        ],
        [ 0.        , -0.        , -8.60502494,         inf]]),
 array([[-1.28718766],
        [ 8.21681692],
        [-9.71758267],
        [-2.63612424]]))