## 3-Input Gates

In [4]:
import numpy as np

In [5]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

def feed_forward(X,W_L1,W_L2):
    
    O_L1 = sigmoid(np.matmul(X,W_L1))
    O_L2 = sigmoid(np.matmul(O_L1,W_L2))
    
    return O_L1,O_L2

def back_propagation(X,alpha,W_L1,W_L2,O_L1,O_L2,expected):
    E_o = O_L2*(1-O_L2)*(expected-O_L2);
    
    E_h = E_o * (O_L1*(1-O_L1)*W_L2.reshape(1,4))
    
    W_L2 = W_L2 + (alpha * E_o * O_L1).reshape(4,1)
    
    X=X.reshape(6,1)

    mask = np.array([[1,1,1,0],[1,1,1,0],[1,1,1,0],[1,0,0,0],[0,1,0,0],[0,0,1,1]])
    W_L1 = ( W_L1 + (alpha * np.matmul(X,E_h)) ) * mask
    
    return W_L1,W_L2
    
def Learn(table,itr,alpha):
    X = table[:,0:3]
    expected = table[:,-1]
    ones = np.ones(24).reshape(8,3)
    X = np.hstack((X,ones))

    mask = np.array([[1,1,1,0],[1,1,1,0],[1,1,1,0],[1,0,0,0],[0,1,0,0],[0,0,1,1]])
    W_L1 = np.random.randn(24).reshape(6,4) * mask
    W_L1[5][3]=np.inf
    W_L2 = np.random.randn(4).reshape(4,1)
    
    for _ in range(itr):
        
        for i in range(8):
            print("Sample(",i,")")
            print(X[i],expected[i])
            O_L1,O_L2 = feed_forward(X[i],W_L1,W_L2)
            print("O_L2=",O_L2)
            W_L1,W_L2 = back_propagation(X[i],alpha,W_L1,W_L2,O_L1,O_L2,expected[i])
        
        print("")
    return W_L1,W_L2




In [6]:
table = np.array([
    [0,0,0,0],
    [0,0,1,1],
    [0,1,0,1],
    [0,1,1,1],
    [1,0,0,1],
    [1,0,1,1],
    [1,1,0,1],
    [1,1,1,0]
])
Learn(table,1000,0.7)

Sample( 0 )
[0. 0. 0. 1. 1. 1.] 0
O_L2= [0.61256014]
Sample( 1 )
[0. 0. 1. 1. 1. 1.] 1
O_L2= [0.54706552]
Sample( 2 )
[0. 1. 0. 1. 1. 1.] 1
O_L2= [0.63604894]
Sample( 3 )
[0. 1. 1. 1. 1. 1.] 1
O_L2= [0.66022516]
Sample( 4 )
[1. 0. 0. 1. 1. 1.] 1
O_L2= [0.64678038]
Sample( 5 )
[1. 0. 1. 1. 1. 1.] 1
O_L2= [0.66630939]
Sample( 6 )
[1. 1. 0. 1. 1. 1.] 1
O_L2= [0.73643275]
Sample( 7 )
[1. 1. 1. 1. 1. 1.] 0
O_L2= [0.74814671]

Sample( 0 )
[0. 0. 0. 1. 1. 1.] 0
O_L2= [0.6809374]
Sample( 1 )
[0. 0. 1. 1. 1. 1.] 1
O_L2= [0.62097269]
Sample( 2 )
[0. 1. 0. 1. 1. 1.] 1
O_L2= [0.6946467]
Sample( 3 )
[0. 1. 1. 1. 1. 1.] 1
O_L2= [0.71187869]
Sample( 4 )
[1. 0. 0. 1. 1. 1.] 1
O_L2= [0.68950957]
Sample( 5 )
[1. 0. 1. 1. 1. 1.] 1
O_L2= [0.70530345]
Sample( 6 )
[1. 1. 0. 1. 1. 1.] 1
O_L2= [0.76512638]
Sample( 7 )
[1. 1. 1. 1. 1. 1.] 0
O_L2= [0.77523791]

Sample( 0 )
[0. 0. 0. 1. 1. 1.] 0
O_L2= [0.71330778]
Sample( 1 )
[0. 0. 1. 1. 1. 1.] 1
O_L2= [0.65826459]
Sample( 2 )
[0. 1. 0. 1. 1. 1.] 1
O_L2= [0.723

(array([[-4.20210591,  1.28256002,  0.94340033,  0.        ],
        [-4.71043961,  1.63143117,  1.24720928,  0.        ],
        [-5.67619692,  2.06255919,  1.98308958,  0.        ],
        [ 1.23924307, -0.        ,  0.        ,  0.        ],
        [ 0.        ,  2.13513559,  0.        ,  0.        ],
        [ 0.        , -0.        , -2.43111805,         inf]]),
 array([[-6.94511331],
        [ 1.56572452],
        [-3.80710992],
        [ 1.81636339]]))