## 3-Input Gates

In [1]:
import numpy as np

In [2]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

def feed_forward(X,W_L1,W_L2):
    
    O_L1 = sigmoid(np.matmul(X,W_L1))
    O_L2 = sigmoid(np.matmul(O_L1,W_L2))
    
    return O_L1,O_L2

def back_propagation(X,alpha,W_L1,W_L2,O_L1,O_L2,expected):
    E_o = O_L2*(1-O_L2)*(expected-O_L2);
    
    E_h = E_o * (O_L1*(1-O_L1)*W_L2.reshape(1,4))
    
    W_L2 = W_L2 + (alpha * E_o * O_L1).reshape(4,1)
    
    X=X.reshape(6,1)

    mask = np.array([[1,1,1,0],[1,1,1,0],[1,1,1,0],[1,0,0,0],[0,1,0,0],[0,0,1,1]])
    W_L1 = ( W_L1 + (alpha * np.matmul(X,E_h)) ) * mask
    
    return W_L1,W_L2
    
def Learn(table,itr,alpha):
    X = table[:,0:3]
    expected = table[:,-1]
    ones = np.ones(24).reshape(8,3)
    X = np.hstack((X,ones))
    print(X)
    mask = np.array([[1,1,1,0],[1,1,1,0],[1,1,1,0],[1,0,0,0],[0,1,0,0],[0,0,1,1]])
    W_L1 = np.random.randn(24).reshape(6,4) * mask
    W_L1[5][3]=np.inf
    W_L2 = np.random.randn(4).reshape(4,1)
    
    for _ in range(itr):
        
        for i in range(8):
            print("\nSample(",i,")")
            print(X[i],expected[i])
            O_L1,O_L2 = feed_forward(X[i],W_L1,W_L2)
            print("O_L1=",O_L1,"\nO_L2=",O_L2)
            W_L1,W_L2 = back_propagation(X[i],alpha,W_L1,W_L2,O_L1,O_L2,expected[i])
            
    return W_L1,W_L2




In [3]:
table = np.array([
    [0,0,0,0],
    [0,0,1,1],
    [0,1,0,1],
    [0,1,1,1],
    [1,0,0,1],
    [1,0,1,1],
    [1,1,0,1],
    [1,1,1,0]
])
Learn(table,1000,0.7)

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 1. 0. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1.]
 [1. 0. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

Sample( 0 )
[0. 0. 0. 1. 1. 1.] 0
O_L1= [0.55875564 0.36319034 0.40137401 1.        ] 
O_L2= [0.1918809]

Sample( 1 )
[0. 0. 1. 1. 1. 1.] 1
O_L1= [0.55618499 0.18507135 0.33195879 1.        ] 
O_L2= [0.18417777]

Sample( 2 )
[0. 1. 0. 1. 1. 1.] 1
O_L1= [0.84484874 0.53887865 0.53789507 1.        ] 
O_L2= [0.15811466]

Sample( 3 )
[0. 1. 1. 1. 1. 1.] 1
O_L1= [0.83592548 0.32066588 0.45832777 1.        ] 
O_L2= [0.17838342]

Sample( 4 )
[1. 0. 0. 1. 1. 1.] 1
O_L1= [0.73745107 0.37976817 0.45050899 1.        ] 
O_L2= [0.22531349]

Sample( 5 )
[1. 0. 1. 1. 1. 1.] 1
O_L1= [0.71902121 0.19987488 0.37251612 1.        ] 
O_L2= [0.25168803]

Sample( 6 )
[1. 1. 0. 1. 1. 1.] 1
O_L1= [0.91757246 0.56495157 0.58136278 1.        ] 
O_L2= [0.27104117]

Sample( 7 )
[1. 1. 1. 1. 1. 1.] 0
O_L1= [0.91010389 0.35074785 0.50040397 1.      

(array([[ 3.51470087e+00,  3.48642589e+00,  2.88604740e-03,
          0.00000000e+00],
        [ 3.50421795e+00,  3.49326596e+00,  1.53350180e-01,
          0.00000000e+00],
        [-7.68084235e+00, -7.82300141e+00, -6.54283339e-01,
          0.00000000e+00],
        [ 2.52551311e+00, -0.00000000e+00, -0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00, -2.02138663e+00, -0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00, -0.00000000e+00, -9.15325319e-01,
                     inf]]),
 array([[-7.83116433],
        [ 8.22245632],
        [ 0.31318463],
        [ 3.8432739 ]]))