## Basic Implementation
### Learning-Gate using 2 Layer

In [1]:
import numpy as np

In [2]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

In [3]:
def feed_forward(X,w11,w12,w21,w22,wh10,wh20,b0,b1,b2):
    oh1 = sigmoid(X[1]*w11+X[2]*w21+b0)
    oh2 = sigmoid(X[1]*w12+X[2]*w22+b1)
    oo = sigmoid(oh1*wh10+oh2*wh20+b2) 
    return (oh1,oh2,oo)


In [4]:
def back_propagate(oo,oh1,oh2,t,w11,w12,w21,w22,wh10,wh20,b0,b1,b2,alpha,X):
    del_o  = oo*(1-oo)*(t-oo)
    del_h1 = oh1*(1-oh1)*(wh10*del_o)
    del_h2 = oh2*(1-oh2)*(wh20*del_o)
    
    b2  = b2  + alpha*del_o*1
    wh10 = wh10 + alpha*del_o*oh1
    wh20 = wh20 + alpha*del_o*oh2
    
    b0 = b0 + alpha*del_h1*1
    b1 = b1 + alpha*del_h2*1
    
    w11 = w11 + alpha*del_h1*X[1]
    w12 = w12 + alpha*del_h2*X[1]
    w21 = w21 + alpha*del_h1*X[2]
    w22 = w22 + alpha*del_h2*X[2]

    return (w11,w12,w21,w22,b0,b1,wh10,wh20,b2)
    

In [5]:
def Learn(itr,table,alpha):
    
    in_table = table[:,0:3]
    
    t = table[:,-1]
    
    (w11,w12,w21,w22,b0,b1,wh10,wh20,b2) = np.random.randn(9)
    for _ in range(itr):
        
        for i in range(4):
            print("Sample(",i,")")
            
            print(in_table[i],t[i])
            oh1,oh2,oo = feed_forward(in_table[i],w11,w12,w21,w22,wh10,wh20,b0,b1,b2)
            w11,w12,w21,w22,b0,b1,wh10,wh20,b2 = back_propagate(oo,oh1,oh2,t[i],w11,w12,w21,w22,wh10,wh20,b0,b1,b2,alpha,in_table[i])
            print(oo)
        print("")
    

In [6]:
#   X0 X1 X2 t
table = np.array([
    [1,0,0,1],
    [1,0,1,0],
    [1,1,0,0],
    [1,1,1,1]
])

In [7]:
Learn(1000,table,1)

Sample( 0 )
[1 0 0] 1
0.9733791048157927
Sample( 1 )
[1 0 1] 0
0.9749066890023809
Sample( 2 )
[1 1 0] 0
0.973775875166826
Sample( 3 )
[1 1 1] 1
0.9734364687756846

Sample( 0 )
[1 0 0] 1
0.9709266511118994
Sample( 1 )
[1 0 1] 0
0.9726104142425663
Sample( 2 )
[1 1 0] 0
0.9711940026854614
Sample( 3 )
[1 1 1] 1
0.9707400059896563

Sample( 0 )
[1 0 0] 1
0.9680178948232137
Sample( 1 )
[1 0 1] 0
0.9698893134985197
Sample( 2 )
[1 1 0] 0
0.968105264881386
Sample( 3 )
[1 1 1] 1
0.9674915236571029

Sample( 0 )
[1 0 0] 1
0.9645220159443458
Sample( 1 )
[1 0 1] 0
0.9666225585932662
Sample( 2 )
[1 1 0] 0
0.964356969676619
Sample( 3 )
[1 1 1] 1
0.9635166260044069

Sample( 0 )
[1 0 0] 1
0.9602567024599136
Sample( 1 )
[1 0 1] 0
0.9626423535960466
Sample( 2 )
[1 1 0] 0
0.9597334555904788
Sample( 3 )
[1 1 1] 1
0.9585651067057405

Sample( 0 )
[1 0 0] 1
0.9549622790694744
Sample( 1 )
[1 0 1] 0
0.9577108256365435
Sample( 2 )
[1 1 0] 0
0.9539230868543126
Sample( 3 )
[1 1 1] 1
0.9522688335268406

Sample( 0 )
[

Sample( 0 )
[1 0 0] 1
0.5096146265046453
Sample( 1 )
[1 0 1] 0
0.5695292662514235
Sample( 2 )
[1 1 0] 0
0.4819111236358153
Sample( 3 )
[1 1 1] 1
0.4361003254475186

Sample( 0 )
[1 0 0] 1
0.5097689984170835
Sample( 1 )
[1 0 1] 0
0.5694360791482572
Sample( 2 )
[1 1 0] 0
0.4818389791589041
Sample( 3 )
[1 1 1] 1
0.43594786316605666

Sample( 0 )
[1 0 0] 1
0.5099240669528164
Sample( 1 )
[1 0 1] 0
0.5693431794021089
Sample( 2 )
[1 1 0] 0
0.4817653984859852
Sample( 3 )
[1 1 1] 1
0.4357949220054877

Sample( 0 )
[1 0 0] 1
0.5100798495739122
Sample( 1 )
[1 0 1] 0
0.5692505598656097
Sample( 2 )
[1 1 0] 0
0.4816903617821261
Sample( 3 )
[1 1 1] 1
0.43564149395775464

Sample( 0 )
[1 0 0] 1
0.5102363642657077
Sample( 1 )
[1 0 1] 0
0.5691582132236743
Sample( 2 )
[1 1 0] 0
0.4816138488946906
Sample( 3 )
[1 1 1] 1
0.43548757076456934

Sample( 0 )
[1 0 0] 1
0.5103936295417185
Sample( 1 )
[1 0 1] 0
0.5690661319885607
Sample( 2 )
[1 1 0] 0
0.48153583934915994
Sample( 3 )
[1 1 1] 1
0.435333143918296

Sample(

Sample( 0 )
[1 0 0] 1
0.5448463845873184
Sample( 1 )
[1 0 1] 0
0.5558549332894842
Sample( 2 )
[1 1 0] 0
0.45323556790275793
Sample( 3 )
[1 1 1] 1
0.40965905242376427

Sample( 0 )
[1 0 0] 1
0.5454811016104286
Sample( 1 )
[1 0 1] 0
0.5556436711779245
Sample( 2 )
[1 1 0] 0
0.4526838547141393
Sample( 3 )
[1 1 1] 1
0.4092990885168804

Sample( 0 )
[1 0 0] 1
0.546127359004511
Sample( 1 )
[1 0 1] 0
0.5554285457311927
Sample( 2 )
[1 1 0] 0
0.45212307368981186
Sample( 3 )
[1 1 1] 1
0.4089350148161373

Sample( 0 )
[1 0 0] 1
0.5467853820085166
Sample( 1 )
[1 0 1] 0
0.5552094697156117
Sample( 2 )
[1 1 0] 0
0.4515530825491727
Sample( 3 )
[1 1 1] 1
0.4085667787294889

Sample( 0 )
[1 0 0] 1
0.5474553978383738
Sample( 1 )
[1 0 1] 0
0.5549863550762079
Sample( 2 )
[1 1 0] 0
0.4509737378559113
Sample( 3 )
[1 1 1] 1
0.4081943286360722

Sample( 0 )
[1 0 0] 1
0.5481376355270734
Sample( 1 )
[1 0 1] 0
0.5547591130064712
Sample( 2 )
[1 1 0] 0
0.4503848951086422
Sample( 3 )
[1 1 1] 1
0.40781761402944217

Sample(

Sample( 0 )
[1 0 0] 1
0.7194231054816324
Sample( 1 )
[1 0 1] 0
0.5066300800901925
Sample( 2 )
[1 1 0] 0
0.3115948110765017
Sample( 3 )
[1 1 1] 1
0.36297511270147914

Sample( 0 )
[1 0 0] 1
0.7211308531854584
Sample( 1 )
[1 0 1] 0
0.5064538160327704
Sample( 2 )
[1 1 0] 0
0.310127284425872
Sample( 3 )
[1 1 1] 1
0.36308491870328574

Sample( 0 )
[1 0 0] 1
0.7228272164284303
Sample( 1 )
[1 0 1] 0
0.5062898432174673
Sample( 2 )
[1 1 0] 0
0.3086642494102346
Sample( 3 )
[1 1 1] 1
0.36320852246308133

Sample( 0 )
[1 0 0] 1
0.7245120163232335
Sample( 1 )
[1 0 1] 0
0.5061381070095993
Sample( 2 )
[1 1 0] 0
0.30720580852384527
Sample( 3 )
[1 1 1] 1
0.36334575919919687

Sample( 0 )
[1 0 0] 1
0.7261850866667244
Sample( 1 )
[1 0 1] 0
0.5059985404166909
Sample( 2 )
[1 1 0] 0
0.30575205840736086
Sample( 3 )
[1 1 1] 1
0.3634964556278456

Sample( 0 )
[1 0 0] 1
0.7278462736693615
Sample( 1 )
[1 0 1] 0
0.5058710644791916
Sample( 2 )
[1 1 0] 0
0.3043030901171984
Sample( 3 )
[1 1 1] 1
0.36366043037444734

Samp

Sample( 0 )
[1 0 0] 1
0.8461050525530053
Sample( 1 )
[1 0 1] 0
0.5253345255755283
Sample( 2 )
[1 1 0] 0
0.1775797597957891
Sample( 3 )
[1 1 1] 1
0.4144097270812199

Sample( 0 )
[1 0 0] 1
0.8466837900266433
Sample( 1 )
[1 0 1] 0
0.5254964529886331
Sample( 2 )
[1 1 0] 0
0.17683498323925986
Sample( 3 )
[1 1 1] 1
0.4147885351933513

Sample( 0 )
[1 0 0] 1
0.8472577845022173
Sample( 1 )
[1 0 1] 0
0.5256562922328711
Sample( 2 )
[1 1 0] 0
0.1760957027000625
Sample( 3 )
[1 1 1] 1
0.41516400840818624

Sample( 0 )
[1 0 0] 1
0.8478270901164647
Sample( 1 )
[1 0 1] 0
0.5258140545277807
Sample( 2 )
[1 1 0] 0
0.17536188344336642
Sample( 3 )
[1 1 1] 1
0.4155361575102417

Sample( 0 )
[1 0 0] 1
0.8483917602562399
Sample( 1 )
[1 0 1] 0
0.5259697518113963
Sample( 2 )
[1 1 0] 0
0.17463349047692112
Sample( 3 )
[1 1 1] 1
0.4159049942555089

Sample( 0 )
[1 0 0] 1
0.8489518475689103
Sample( 1 )
[1 0 1] 0
0.5261233966980511
Sample( 2 )
[1 1 0] 0
0.17391048856868077
Sample( 3 )
[1 1 1] 1
0.4162705313248953

Sampl

Sample( 0 )
[1 0 0] 1
0.8923816070702939
Sample( 1 )
[1 0 1] 0
0.5345311580484202
Sample( 2 )
[1 1 0] 0
0.11776349735648456
Sample( 3 )
[1 1 1] 1
0.4418158449538355

Sample( 0 )
[1 0 0] 1
0.8926348344332827
Sample( 1 )
[1 0 1] 0
0.5345569090611046
Sample( 2 )
[1 1 0] 0
0.11744308977172825
Sample( 3 )
[1 1 1] 1
0.44194087205693233

Sample( 0 )
[1 0 0] 1
0.8928866096157775
Sample( 1 )
[1 0 1] 0
0.5345822474943044
Sample( 2 )
[1 1 0] 0
0.11712466566688423
Sample( 3 )
[1 1 1] 1
0.44206485552680674

Sample( 0 )
[1 0 0] 1
0.8931369448710968
Sample( 1 )
[1 0 1] 0
0.5346071796848652
Sample( 2 )
[1 1 0] 0
0.11680820778883629
Sample( 3 )
[1 1 1] 1
0.4421878066898328

Sample( 0 )
[1 0 0] 1
0.8933858523216914
Sample( 1 )
[1 0 1] 0
0.5346317118688316
Sample( 2 )
[1 1 0] 0
0.11649369905889106
Sample( 3 )
[1 1 1] 1
0.4423097367339089

Sample( 0 )
[1 0 0] 1
0.8936333439608017
Sample( 1 )
[1 0 1] 0
0.5346558501829927
Sample( 2 )
[1 1 0] 0
0.1161811225711173
Sample( 3 )
[1 1 1] 1
0.44243065671004606

Sa

Sample( 0 )
[1 0 0] 1
0.9150126106251019
Sample( 1 )
[1 0 1] 0
0.5358595741185128
Sample( 2 )
[1 1 0] 0
0.08978112162941947
Sample( 3 )
[1 1 1] 1
0.4516722292438067

Sample( 0 )
[1 0 0] 1
0.9151524281857156
Sample( 1 )
[1 0 1] 0
0.5358622762449654
Sample( 2 )
[1 1 0] 0
0.08961269720707114
Sample( 3 )
[1 1 1] 1
0.4517248501608121

Sample( 0 )
[1 0 0] 1
0.9152916521558266
Sample( 1 )
[1 0 1] 0
0.5358649081272094
Sample( 2 )
[1 1 0] 0
0.08944504549779649
Sample( 3 )
[1 1 1] 1
0.45177714793168466

Sample( 0 )
[1 0 0] 1
0.9154302864033211
Sample( 1 )
[1 0 1] 0
0.5358674707483864
Sample( 2 )
[1 1 0] 0
0.089278161154714
Sample( 3 )
[1 1 1] 1
0.4518291253150502

Sample( 0 )
[1 0 0] 1
0.9155683347630628
Sample( 1 )
[1 0 1] 0
0.5358699650774402
Sample( 2 )
[1 1 0] 0
0.08911203887875402
Sample( 3 )
[1 1 1] 1
0.45188078504010476

Sample( 0 )
[1 0 0] 1
0.915705801037233
Sample( 1 )
[1 0 1] 0
0.5358723920693411
Sample( 2 )
[1 1 0] 0
0.08894667341815153
Sample( 3 )
[1 1 1] 1
0.45193212980698355

Samp


Sample( 0 )
[1 0 0] 1
0.9284202979777827
Sample( 1 )
[1 0 1] 0
0.5358735725886477
Sample( 2 )
[1 1 0] 0
0.07389996833503458
Sample( 3 )
[1 1 1] 1
0.4562675277407971

Sample( 0 )
[1 0 0] 1
0.9285094141956927
Sample( 1 )
[1 0 1] 0
0.53587217575718
Sample( 2 )
[1 1 0] 0
0.07379627051099849
Sample( 3 )
[1 1 1] 1
0.45629506834980077

Sample( 0 )
[1 0 0] 1
0.9285982356309038
Sample( 1 )
[1 0 1] 0
0.535870766231237
Sample( 2 )
[1 1 0] 0
0.07369294054462565
Sample( 3 )
[1 1 1] 1
0.4563224790383419

Sample( 0 )
[1 0 0] 1
0.9286867638126017
Sample( 1 )
[1 0 1] 0
0.5358693442026294
Sample( 2 )
[1 1 0] 0
0.07358997641819036
Sample( 3 )
[1 1 1] 1
0.45634976067608357

Sample( 0 )
[1 0 0] 1
0.9287750002593654
Sample( 1 )
[1 0 1] 0
0.5358679098607169
Sample( 2 )
[1 1 0] 0
0.07348737612865712
Sample( 3 )
[1 1 1] 1
0.45637691412524917

Sample( 0 )
[1 0 0] 1
0.9288629464792582
Sample( 1 )
[1 0 1] 0
0.535866463392441
Sample( 2 )
[1 1 0] 0
0.07338513768754933
Sample( 3 )
[1 1 1] 1
0.45640394024069714

Sam


Sample( 0 )
[1 0 0] 1
0.9373663196047303
Sample( 1 )
[1 0 1] 0
0.5356539384190594
Sample( 2 )
[1 1 0] 0
0.06361592298644841
Sample( 3 )
[1 1 1] 1
0.4588397576721814

Sample( 0 )
[1 0 0] 1
0.9374286049695136
Sample( 1 )
[1 0 1] 0
0.5356519002713301
Sample( 2 )
[1 1 0] 0
0.06354522122376718
Sample( 3 )
[1 1 1] 1
0.4588563191644804

Sample( 0 )
[1 0 0] 1
0.937490722918175
Sample( 1 )
[1 0 1] 0
0.5356498613405505
Sample( 2 )
[1 1 0] 0
0.06347472201106243
Sample( 3 )
[1 1 1] 1
0.4588728178043605

Sample( 0 )
[1 0 0] 1
0.9375526741648469
Sample( 1 )
[1 0 1] 0
0.5356478216690462
Sample( 2 )
[1 1 0] 0
0.0634044244396372
Sample( 3 )
[1 1 1] 1
0.4588892539336993

Sample( 0 )
[1 0 0] 1
0.9376144594195434
Sample( 1 )
[1 0 1] 0
0.5356457812986122
Sample( 2 )
[1 1 0] 0
0.0633343276062703
Sample( 3 )
[1 1 1] 1
0.45890562789197326

Sample( 0 )
[1 0 0] 1
0.9376760793881918
Sample( 1 )
[1 0 1] 0
0.5356437402705176
Sample( 2 )
[1 1 0] 0
0.06326443061317458
Sample( 3 )
[1 1 1] 1
0.4589219400162812

Sampl