## Matrix Implementation
### Learning-Gate using 2 Layer

In [24]:
import numpy as np

In [25]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

In [26]:
def feed_forward(X,W_L1,W_L2):
    
    O_L1 = sigmoid(np.matmul(X,W_L1))
    O_L2 = sigmoid(np.matmul(O_L1,W_L2))
    
    return O_L1,O_L2
    
    

In [27]:
def back_propagation(X,alpha,W_L1,W_L2,O_L1,O_L2,expected):
    E_o = O_L2*(1-O_L2)*(expected-O_L2);
    
    E_h = E_o * (O_L1*(1-O_L1)*W_L2.reshape(1,3))
    
    W_L2 = W_L2 + (alpha * E_o * O_L1).reshape(3,1)
    
    X=X.reshape(4,1)

    mask = np.array([[1,1,0],[1,1,0],[1,0,0],[0,1,1]])
    W_L1 = ( W_L1 + (alpha * np.matmul(X,E_h)) ) * mask
    
    return W_L1,W_L2
    

In [28]:
def Learn(table,itr,alpha):
    X = table[:,0:2]
    expected = table[:,-1]
    ones = np.ones(8).reshape(4,2)
    X = np.hstack((X,ones))
    print(X)
    mask = np.array([[1,1,0],[1,1,0],[1,0,0],[0,1,1]])
    W_L1 = np.random.randn(12).reshape(4,3) * mask
    W_L1[3][2]=np.inf
    W_L2 = np.random.randn(3).reshape(3,1)

    for _ in range(itr):
        
        for i in range(4):
            print("\nSample(",i,")")
            print(X[i],expected[i])
            O_L1,O_L2 = feed_forward(X[i],W_L1,W_L2)
            print("O_L1=",O_L1,"\nO_L2=",O_L2)
            W_L1,W_L2 = back_propagation(X[i],alpha,W_L1,W_L2,O_L1,O_L2,expected[i])
            
    return W_L1,W_L2
    

In [29]:
table = np.array([
    [0,0,1],
    [0,1,0],
    [1,0,0],
    [1,1,1]
])
Learn(table,1000,1)

[[0. 0. 1. 1.]
 [0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 1. 1.]]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.41778164 0.74021212 1.        ] 
O_L2= [0.57100751]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.53218451 0.82230654 1.        ] 
O_L2= [0.60103132]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [0.19733454 0.68165884 1.        ] 
O_L2= [0.59722152]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.30144414 0.76787164 1.        ] 
O_L2= [0.52567573]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.41910356 0.73854065 1.        ] 
O_L2= [0.54325029]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.53471147 0.82033321 1.        ] 
O_L2= [0.57543467]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [0.19732088 0.67851458 1.        ] 
O_L2= [0.57677536]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.30296836 0.76516137 1.        ] 
O_L2= [0.5041768]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.41933177 0.73722061 1.        ] 
O_L2= [0.52427982]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.53586721 0.81871271 1.        ] 
O_L2= [0.55764041]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [0.19

O_L2= [0.4792732]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.29893311 0.68980124 1.        ] 
O_L2= [0.49049303]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.51029575 0.7591621  1.        ] 
O_L2= [0.4800025]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [0.07359704 0.56851931 1.        ] 
O_L2= [0.55462408]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.17669071 0.64023298 1.        ] 
O_L2= [0.47968837]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.29684431 0.68903404 1.        ] 
O_L2= [0.49082155]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.51103198 0.75830982 1.        ] 
O_L2= [0.47877121]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [0.07203766 0.56671418 1.        ] 
O_L2= [0.55527053]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.17522038 0.63821719 1.        ] 
O_L2= [0.48011416]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.29475429 0.68826892 1.        ] 
O_L2= [0.49116351]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.51180654 0.75746792 1.        ] 
O_L2= [0.4775153]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [0.07049635 0.56490817 1.        ] 
O_L2= [0.5559

O_L1= [0.62512221 0.75792245 1.        ] 
O_L2= [0.33883781]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [0.01052865 0.43691172 1.        ] 
O_L2= [0.61982659]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.09162827 0.54423285 1.        ] 
O_L2= [0.5465335]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.15957501 0.65065472 1.        ] 
O_L2= [0.56095933]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.62706048 0.75935239 1.        ] 
O_L2= [0.33642506]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [0.01019706 0.43477342 1.        ] 
O_L2= [0.62051764]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.09062187 0.54398976 1.        ] 
O_L2= [0.54795243]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.15791798 0.65049548 1.        ] 
O_L2= [0.56257547]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.62898705 0.76083927 1.        ] 
O_L2= [0.33402658]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [0.00987639 0.43262553 1.        ] 
O_L2= [0.62117534]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.08962532 0.54379823 1.        ] 
O_L2= [0.54937187]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.15

[1. 1. 1. 1.] 1
O_L1= [0.04928638 0.68343099 1.        ] 
O_L2= [0.66125995]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.08603662 0.70151743 1.        ] 
O_L2= [0.66290805]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.74305707 0.94223665 1.        ] 
O_L2= [0.22484809]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [0.00158833 0.26952006 1.        ] 
O_L2= [0.52381373]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04905862 0.68708014 1.        ] 
O_L2= [0.66383979]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.08549428 0.70320713 1.        ] 
O_L2= [0.66455611]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.7447238  0.94430444 1.        ] 
O_L2= [0.22379741]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [0.00155705 0.26686715 1.        ] 
O_L2= [0.51958625]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.0488401  0.69071408 1.        ] 
O_L2= [0.66645627]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.08496344 0.70491512 1.        ] 
O_L2= [0.66623114]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.74639223 0.94630873 1.        ] 
O_L2= [0.22274763]

Sample( 2 )
[1. 0. 1. 

O_L1= [6.37445495e-04 1.48127799e-01 1.00000000e+00] 
O_L2= [0.24615049]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04636033 0.84863022 1.        ] 
O_L2= [0.83411619]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.06609328 0.82001973 1.        ] 
O_L2= [0.80677726]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.84159545 0.99376539 1.        ] 
O_L2= [0.147081]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [6.32958535e-04 1.47423630e-01 1.00000000e+00] 
O_L2= [0.24406657]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.0463764  0.84956405 1.        ] 
O_L2= [0.8353944]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.06597397 0.82101041 1.        ] 
O_L2= [0.80816274]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.8423505  0.99387898 1.        ] 
O_L2= [0.14626671]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [6.28552283e-04 1.46732643e-01 1.00000000e+00] 
O_L2= [0.24201904]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04639207 0.85048018 1.        ] 
O_L2= [0.83665063]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.06585621 0.82198575 1.        ] 
O_L2= [0.80952854]

Sampl

[1. 0. 1. 1.] 0
O_L1= [4.29802914e-04 1.16228316e-01 1.00000000e+00] 
O_L2= [0.15161762]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04647113 0.89023213 1.        ] 
O_L2= [0.89298096]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.05967732 0.86706101 1.        ] 
O_L2= [0.87414349]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.87715885 0.9976057  1.        ] 
O_L2= [0.10394308]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [4.28226819e-04 1.15990419e-01 1.00000000e+00] 
O_L2= [0.1509359]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04646224 0.89053206 1.        ] 
O_L2= [0.89341695]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.05961917 0.8674171  1.        ] 
O_L2= [0.87466186]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.8774269  0.99762519 1.        ] 
O_L2= [0.1035803]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [4.26666512e-04 1.15754911e-01 1.00000000e+00] 
O_L2= [0.15026177]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.0464532  0.89082874 1.        ] 
O_L2= [0.89384832]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.05956141 0.8677695  1.        ] 
O_L2= [0

O_L1= [0.04546974 0.9075432  1.        ] 
O_L2= [0.9182898]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.05587007 0.88784602 1.        ] 
O_L2= [0.90440519]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.89283268 0.99856805 1.        ] 
O_L2= [0.08188575]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [3.35916771e-04 1.01975081e-01 1.00000000e+00] 
O_L2= [0.11245486]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04545624 0.90768824 1.        ] 
O_L2= [0.91850253]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.05583372 0.88802178 1.        ] 
O_L2= [0.90466024]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.89296572 0.99857479 1.        ] 
O_L2= [0.08169206]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [3.35125364e-04 1.01853235e-01 1.00000000e+00] 
O_L2= [0.1121377]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04544274 0.90783226 1.        ] 
O_L2= [0.91871377]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.05579754 0.88819633 1.        ] 
O_L2= [0.9049135]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.89309786 0.99858146 1.        ] 
O_L2= [0.08149961]

Sample( 2 )
[1. 0

O_L2= [0.9208682]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.90150688 0.99896277 1.        ] 
O_L2= [0.06910911]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [2.84254446e-04 9.38906601e-02 1.00000000e+00] 
O_L2= [0.09221123]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04435408 0.91701704 1.        ] 
O_L2= [0.93216228]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.05330396 0.89936404 1.        ] 
O_L2= [0.92102203]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.90158903 0.99896609 1.        ] 
O_L2= [0.06898708]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [2.83765840e-04 9.38126225e-02 1.00000000e+00] 
O_L2= [0.09202419]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04434132 0.91710474 1.        ] 
O_L2= [0.93229026]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.05327826 0.89947097 1.        ] 
O_L2= [0.92117506]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.90167077 0.99896939 1.        ] 
O_L2= [0.06886563]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [2.83279686e-04 9.37349407e-02 1.00000000e+00] 
O_L2= [0.09183818]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04432857

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [2.50559054e-04 8.84128215e-02 1.00000000e+00] 
O_L2= [0.07950284]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04335516 0.92305832 1.        ] 
O_L2= [0.94093874]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.05143929 0.90673877 1.        ] 
O_L2= [0.93149689]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.9072539 0.9991776 1.       ] 
O_L2= [0.06056131]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [2.50222387e-04 8.83569766e-02 1.00000000e+00] 
O_L2= [0.07937778]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04334389 0.92311869 1.        ] 
O_L2= [0.94102594]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.05141965 0.90681255 1.        ] 
O_L2= [0.93160074]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.90731089 0.99917956 1.        ] 
O_L2= [0.06047663]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [2.49887067e-04 8.83013303e-02 1.00000000e+00] 
O_L2= [0.07925327]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04333264 0.92317882 1.        ] 
O_L2= [0.94111278]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.05140007 0.90688603 1.        

[1. 1. 1. 1.] 1
O_L1= [0.04247844 0.92737774 1.        ] 
O_L2= [0.94714255]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.04998025 0.91202035 1.        ] 
O_L2= [0.93887182]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.911353  0.9993101 1.       ] 
O_L2= [0.05449161]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [2.26269093e-04 8.43143682e-02 1.00000000e+00] 
O_L2= [0.07057579]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04246857 0.92742256 1.        ] 
O_L2= [0.9472065]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.04996452 0.91207518 1.        ] 
O_L2= [0.93894769]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.91139578 0.99931139 1.        ] 
O_L2= [0.05442858]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [2.26021163e-04 8.42717464e-02 1.00000000e+00] 
O_L2= [0.07048566]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04245872 0.92746724 1.        ] 
O_L2= [0.94727023]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.04994882 0.91212984 1.        ] 
O_L2= [0.9390233]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.91143843 0.99931268 1.        ] 
O_L2= [0.05436575]

Sam

O_L1= [0.04879155 0.91604619 1.        ] 
O_L2= [0.9443979]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.91450802 0.9994011  1.        ] 
O_L2= [0.04986929]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [2.08129266e-04 8.11472386e-02 1.00000000e+00] 
O_L2= [0.06403308]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.041701   0.93070277 1.        ] 
O_L2= [0.95185716]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.04877852 0.91608905 1.        ] 
O_L2= [0.94445622]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.91454177 0.99940202 1.        ] 
O_L2= [0.04982017]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [2.07936937e-04 8.11130958e-02 1.00000000e+00] 
O_L2= [0.06396426]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04169234 0.9307377  1.        ] 
O_L2= [0.95190634]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.04876552 0.9161318  1.        ] 
O_L2= [0.94451437]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.91457544 0.99940294 1.        ] 
O_L2= [0.04977119]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [2.07745151e-04 8.10790368e-02 1.00000000e+00] 
O_L2= [0.06389566]

Sam

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [1.93809281e-04 7.85689528e-02 1.00000000e+00] 
O_L2= [0.05894135]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04102325 0.93331411 1.        ] 
O_L2= [0.95551096]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.04778343 0.91928541 1.        ] 
O_L2= [0.94877053]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.91706958 0.99946833 1.        ] 
O_L2= [0.04616693]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [1.93654757e-04 7.85407108e-02 1.00000000e+00] 
O_L2= [0.05888675]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04101556 0.93334243 1.        ] 
O_L2= [0.9555503]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.04777239 0.91932007 1.        ] 
O_L2= [0.94881692]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.91709712 0.99946902 1.        ] 
O_L2= [0.04612744]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [1.93500613e-04 7.85125289e-02 1.00000000e+00] 
O_L2= [0.0588323]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04100789 0.93337067 1.        ] 
O_L2= [0.95558955]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.04776136 0.91935465 1.       

[1. 1. 1. 1.] 1
O_L1= [0.04041962 0.93546025 1.        ] 
O_L2= [0.95847456]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.04693004 0.92191254 1.        ] 
O_L2= [0.95226048]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.91916441 0.99951909 1.        ] 
O_L2= [0.0431837]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [1.82022453e-04 7.63864593e-02 1.00000000e+00] 
O_L2= [0.05479808]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04041275 0.93548384 1.        ] 
O_L2= [0.95850692]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.04692047 0.92194141 1.        ] 
O_L2= [0.95229853]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.91918753 0.99951963 1.        ] 
O_L2= [0.04315103]

Sample( 2 )
[1. 0. 1. 1.] 0
O_L1= [1.81895218e-04 7.63625744e-02 1.00000000e+00] 
O_L2= [0.05475359]

Sample( 3 )
[1. 1. 1. 1.] 1
O_L1= [0.04040588 0.93550738 1.        ] 
O_L2= [0.9585392]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L1= [0.04691093 0.92197023 1.        ] 
O_L2= [0.9523365]

Sample( 1 )
[0. 1. 1. 1.] 0
O_L1= [0.9192106  0.99952017 1.        ] 
O_L2= [0.04311844]

S

(array([[-5.62966891, -5.00649043,  0.        ],
        [ 5.47428469,  5.21299234,  0.        ],
        [-3.02393226,  0.        ,  0.        ],
        [-0.        ,  2.49262826,         inf]]),
 array([[-7.72948924],
        [ 7.4238585 ],
        [-3.45499985]]))