## Matrix Implementation
### Learning-Gate using 2 Layer

In [1]:
import numpy as np

In [2]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

In [3]:
def feed_forward(X,W_L1,W_L2):
    
    O_L1 = sigmoid(np.matmul(X,W_L1))
    O_L2 = sigmoid(np.matmul(O_L1,W_L2))
    
    return O_L1,O_L2
    
    

In [4]:
def back_propagation(X,alpha,W_L1,W_L2,O_L1,O_L2,expected):
    E_o = O_L2*(1-O_L2)*(expected-O_L2);
    
    E_h = E_o * (O_L1*(1-O_L1)*W_L2.reshape(1,3))
    
    W_L2 = W_L2 + (alpha * E_o * O_L1).reshape(3,1)
    
    X=X.reshape(4,1)

    mask = np.array([[1,1,0],[1,1,0],[1,0,0],[0,1,1]])
    W_L1 = ( W_L1 + (alpha * np.matmul(X,E_h)) ) * mask
    
    return W_L1,W_L2
    

In [5]:
def Learn(table,itr,alpha):
    X = table[:,0:2]
    expected = table[:,-1]
    ones = np.ones(8).reshape(4,2)
    X = np.hstack((X,ones))

    mask = np.array([[1,1,0],[1,1,0],[1,0,0],[0,1,1]])
    W_L1 = np.random.randn(12).reshape(4,3) * mask
    W_L1[3][2]=np.inf
    W_L2 = np.random.randn(3).reshape(3,1)

    for _ in range(itr):
        
        for i in range(4):
            print("Sample(",i,")")
            print(X[i],expected[i])
            O_L1,O_L2 = feed_forward(X[i],W_L1,W_L2)
            print("O_L2=",O_L2)
            W_L1,W_L2 = back_propagation(X[i],alpha,W_L1,W_L2,O_L1,O_L2,expected[i])
        print("")
    return W_L1,W_L2
    

In [6]:
table = np.array([
    [0,0,1],
    [0,1,0],
    [1,0,0],
    [1,1,1]
])
Learn(table,1000,1)

Sample( 0 )
[0. 0. 1. 1.] 1
O_L2= [0.69304131]
Sample( 1 )
[0. 1. 1. 1.] 0
O_L2= [0.66473107]
Sample( 2 )
[1. 0. 1. 1.] 0
O_L2= [0.69898696]
Sample( 3 )
[1. 1. 1. 1.] 1
O_L2= [0.61219336]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L2= [0.65391995]
Sample( 1 )
[0. 1. 1. 1.] 0
O_L2= [0.63247258]
Sample( 2 )
[1. 0. 1. 1.] 0
O_L2= [0.66237107]
Sample( 3 )
[1. 1. 1. 1.] 1
O_L2= [0.57683928]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L2= [0.61984968]
Sample( 1 )
[0. 1. 1. 1.] 0
O_L2= [0.60500245]
Sample( 2 )
[1. 0. 1. 1.] 0
O_L2= [0.63100199]
Sample( 3 )
[1. 1. 1. 1.] 1
O_L2= [0.54819854]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L2= [0.59173258]
Sample( 1 )
[0. 1. 1. 1.] 0
O_L2= [0.58262654]
Sample( 2 )
[1. 0. 1. 1.] 0
O_L2= [0.60534634]
Sample( 3 )
[1. 1. 1. 1.] 1
O_L2= [0.5258271]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L2= [0.56936956]
Sample( 1 )
[0. 1. 1. 1.] 0
O_L2= [0.56495851]
Sample( 2 )
[1. 0. 1. 1.] 0
O_L2= [0.58500656]
Sample( 3 )
[1. 1. 1. 1.] 1
O_L2= [0.50874152]

Sample( 0 )
[0. 0. 1. 1.] 1
O_L2= [0.55199431]
Sample( 1

(array([[ 5.02804167, -5.45926462,  0.        ],
        [-5.32552418,  5.3771995 ,  0.        ],
        [-2.80549466, -0.        ,  0.        ],
        [-0.        , -3.07367735,         inf]]),
 array([[-7.59149765],
        [-7.56181813],
        [ 3.735533  ]]))