## Matrix Implementation
### Learning-Gate using 2 Layer

In [21]:
import numpy as np
from sklearn.metrics import mean_squared_error

In [22]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

In [23]:
def feed_forward(X,W_L1,W_L2):
    
    O_L1 = sigmoid(np.matmul(X,W_L1))
    O_L2 = sigmoid(np.matmul(O_L1,W_L2))
    
    return O_L1,O_L2
    
    

In [24]:
def back_propagation(X,alpha,W_L1,W_L2,O_L1,O_L2,expected):
    E_o = O_L2*(1-O_L2)*(expected-O_L2);
    
    E_h = E_o * (O_L1*(1-O_L1)*W_L2.reshape(1,3))
    
    W_L2 = W_L2 + (alpha * E_o * O_L1).reshape(3,1)
    
    X=X.reshape(4,1)

    mask = np.array([[1,1,0],[1,1,0],[1,0,0],[0,1,1]])
    W_L1 = ( W_L1 + (alpha * np.matmul(X,E_h)) ) * mask
    
    return W_L1,W_L2
    

In [25]:
def Learn(table,itr,alpha):
    X = table[:,0:2]
    expected = table[:,-1]
    ones = np.ones(8).reshape(4,2)
    X = np.hstack((X,ones))

    mask = np.array([[1,1,0],[1,1,0],[1,0,0],[0,1,1]])
    W_L1 = np.random.randn(12).reshape(4,3) * mask
    W_L1[3][2]=np.inf
    W_L2 = np.random.randn(3).reshape(3,1)

    for _ in range(itr):
        out = np.ones(4)
        for i in range(4):
            O_L1,O_L2 = feed_forward(X[i],W_L1,W_L2)
            W_L1,W_L2 = back_propagation(X[i],alpha,W_L1,W_L2,O_L1,O_L2,expected[i])
            out[i]=O_L2
        Er = mean_squared_error(expected,out)
        if(Er<0.02):
            print(Er)
            print(out)
            break
    return W_L1,W_L2
    

In [27]:
table = np.array([
    [0,0,1],
    [0,1,0],
    [1,0,0],
    [1,1,1]
])
Learn(table,1000,1)

0.01990864259731142
[0.87954988 0.13754411 0.13874032 0.83580779]


(array([[ 2.97944367,  5.32924356,  0.        ],
        [ 2.93583645,  5.43130401,  0.        ],
        [-4.38881417, -0.        ,  0.        ],
        [ 0.        , -1.79264399,         inf]]),
 array([[ 5.93406863],
        [-5.89480521],
        [ 2.76065898]]))